In [1]:
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_csv("student_habits_performance.csv")
df.head()

,student_id,age,gender,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,extracurricular_participation,exam_score
0,S1000,23,Female,0.0,1.2,1.1,No,85.0,8.0,Fair,6,Master,Average,8,Yes,56.2
1,S1001,20,Female,6.9,2.8,2.3,No,97.3,4.6,Good,6,High School,Average,8,No,100.0
2,S1002,21,Male,1.4,3.1,1.3,No,94.8,8.0,Poor,1,High School,Poor,1,No,34.3
3,S1003,23,Female,1.0,3.9,1.0,No,71.0,9.2,Poor,4,Master,Good,1,Yes,26.8
4,S1004,19,Female,5.0,4.4,0.5,No,90.9,4.9,Fair,3,Master,Good,1,No,66.4

In [3]:
df.isnull().sum()

student_id                        0
age                               0
gender                            0
study_hours_per_day               0
social_media_hours                0
netflix_hours                     0
part_time_job                     0
attendance_percentage             0
sleep_hours                       0
diet_quality                      0
exercise_frequency                0
parental_education_level         91
internet_quality                  0
mental_health_rating              0
extracurricular_participation     0
exam_score                        0
dtype: int64

In [4]:
df["parental_education_level"].unique()

<StringArray>
['Master', 'High School', 'Bachelor', nan]
Length: 4, dtype: str

In [5]:
clean_df = df["parental_education_level"].fillna("Illetrate" , inplace=True)

C:\Users\hp\AppData\Local\Temp\ipykernel_7096\53831720.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  clean_df = df["parental_education_level"].fillna("Illetrate" , inplace=True)

In [6]:
df.head()

,student_id,age,gender,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,extracurricular_participation,exam_score
0,S1000,23,Female,0.0,1.2,1.1,No,85.0,8.0,Fair,6,Master,Average,8,Yes,56.2
1,S1001,20,Female,6.9,2.8,2.3,No,97.3,4.6,Good,6,High School,Average,8,No,100.0
2,S1002,21,Male,1.4,3.1,1.3,No,94.8,8.0,Poor,1,High School,Poor,1,No,34.3
3,S1003,23,Female,1.0,3.9,1.0,No,71.0,9.2,Poor,4,Master,Good,1,Yes,26.8
4,S1004,19,Female,5.0,4.4,0.5,No,90.9,4.9,Fair,3,Master,Good,1,No,66.4

In [7]:
df.fillna({"parental_education_level" : "UnEducated"} , inplace=True)

,student_id,age,gender,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,extracurricular_participation,exam_score
0,S1000,23,Female,0.0,1.2,1.1,No,85.0,8.0,Fair,6,Master,Average,8,Yes,56.2
1,S1001,20,Female,6.9,2.8,2.3,No,97.3,4.6,Good,6,High School,Average,8,No,100.0
2,S1002,21,Male,1.4,3.1,1.3,No,94.8,8.0,Poor,1,High School,Poor,1,No,34.3
3,S1003,23,Female,1.0,3.9,1.0,No,71.0,9.2,Poor,4,Master,Good,1,Yes,26.8
4,S1004,19,Female,5.0,4.4,0.5,No,90.9,4.9,Fair,3,Master,Good,1,No,66.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,S1995,21,Female,2.6,0.5,1.6,No,77.0,7.5,Fair,2,High School,Good,6,Yes,76.1
996,S1996,17,Female,2.9,1.0,2.4,Yes,86.0,6.8,Poor,1,High School,Average,6,Yes,65.9
997,S1997,20,Male,3.0,2.6,1.3,No,61.9,6.5,Good,5,Bachelor,Good,9,Yes,64.4
998,S1998,24,Male,5.4,4.1,1.1,Yes,100.0,7.6,Fair,0,Bachelor,Average,1,No,69.7
999,S1999,19,Female,4.3,2.9,1.9,No,89.4,7.1,Good,2,Bachelor,Average,8,No,74.9

In [8]:
df.head()

,student_id,age,gender,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,extracurricular_participation,exam_score
0,S1000,23,Female,0.0,1.2,1.1,No,85.0,8.0,Fair,6,Master,Average,8,Yes,56.2
1,S1001,20,Female,6.9,2.8,2.3,No,97.3,4.6,Good,6,High School,Average,8,No,100.0
2,S1002,21,Male,1.4,3.1,1.3,No,94.8,8.0,Poor,1,High School,Poor,1,No,34.3
3,S1003,23,Female,1.0,3.9,1.0,No,71.0,9.2,Poor,4,Master,Good,1,Yes,26.8
4,S1004,19,Female,5.0,4.4,0.5,No,90.9,4.9,Fair,3,Master,Good,1,No,66.4

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   student_id                     1000 non-null   str
 1   age                            1000 non-null   int64
 2   gender                         1000 non-null   str
 3   study_hours_per_day            1000 non-null   float64
 4   social_media_hours             1000 non-null   float64
 5   netflix_hours                  1000 non-null   float64
 6   part_time_job                  1000 non-null   str
 7   attendance_percentage          1000 non-null   float64
 8   sleep_hours                    1000 non-null   float64
 9   diet_quality                   1000 non-null   str
 10  exercise_frequency             1000 non-null   int64
 11  parental_education_level       1000 non-null   str
 12  internet_quality               1000 non-null   str
 13  mental_health_rating           1000 non-null   int64
 14  extracurricular_participation  1000 non-null   str
 15  exam_score                     1000 non-null   float64
dtypes: float64(6), int64(3), str(7)
memory usage: 125.1 KB

In [10]:
df.drop(columns = ["student_id"] , inplace= True)

In [11]:
df.head()

,age,gender,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,extracurricular_participation,exam_score
0,23,Female,0.0,1.2,1.1,No,85.0,8.0,Fair,6,Master,Average,8,Yes,56.2
1,20,Female,6.9,2.8,2.3,No,97.3,4.6,Good,6,High School,Average,8,No,100.0
2,21,Male,1.4,3.1,1.3,No,94.8,8.0,Poor,1,High School,Poor,1,No,34.3
3,23,Female,1.0,3.9,1.0,No,71.0,9.2,Poor,4,Master,Good,1,Yes,26.8
4,19,Female,5.0,4.4,0.5,No,90.9,4.9,Fair,3,Master,Good,1,No,66.4

In [12]:

en_df = pd.get_dummies(df)

In [13]:
en_df.head()

,age,study_hours_per_day,social_media_hours,netflix_hours,attendance_percentage,sleep_hours,exercise_frequency,mental_health_rating,exam_score,gender_Female,...,diet_quality_Poor,parental_education_level_Bachelor,parental_education_level_High School,parental_education_level_Master,parental_education_level_UnEducated,internet_quality_Average,internet_quality_Good,internet_quality_Poor,extracurricular_participation_No,extracurricular_participation_Yes
0,23,0.0,1.2,1.1,85.0,8.0,6,8,56.2,True,...,False,False,False,True,False,True,False,False,False,True
1,20,6.9,2.8,2.3,97.3,4.6,6,8,100.0,True,...,False,False,True,False,False,True,False,False,True,False
2,21,1.4,3.1,1.3,94.8,8.0,1,1,34.3,False,...,True,False,True,False,False,False,False,True,True,False
3,23,1.0,3.9,1.0,71.0,9.2,4,1,26.8,True,...,True,False,False,True,False,False,True,False,False,True
4,19,5.0,4.4,0.5,90.9,4.9,3,1,66.4,True,...,False,False,False,True,False,False,True,False,True,False

In [14]:
X = en_df.drop("exam_score" , axis = 1)
y = en_df["exam_score"]

In [15]:
X.head()

,age,study_hours_per_day,social_media_hours,netflix_hours,attendance_percentage,sleep_hours,exercise_frequency,mental_health_rating,gender_Female,gender_Male,...,diet_quality_Poor,parental_education_level_Bachelor,parental_education_level_High School,parental_education_level_Master,parental_education_level_UnEducated,internet_quality_Average,internet_quality_Good,internet_quality_Poor,extracurricular_participation_No,extracurricular_participation_Yes
0,23,0.0,1.2,1.1,85.0,8.0,6,8,True,False,...,False,False,False,True,False,True,False,False,False,True
1,20,6.9,2.8,2.3,97.3,4.6,6,8,True,False,...,False,False,True,False,False,True,False,False,True,False
2,21,1.4,3.1,1.3,94.8,8.0,1,1,False,True,...,True,False,True,False,False,False,False,True,True,False
3,23,1.0,3.9,1.0,71.0,9.2,4,1,True,False,...,True,False,False,True,False,False,True,False,False,True
4,19,5.0,4.4,0.5,90.9,4.9,3,1,True,False,...,False,False,False,True,False,False,True,False,True,False

In [16]:
y.head()

0     56.2
1    100.0
2     34.3
3     26.8
4     66.4
Name: exam_score, dtype: float64

In [17]:
from sklearn.model_selection import train_test_split

X_train , X_test  , y_train , y_test = train_test_split( X , y  , test_size = 0.2 , random_state=42)

In [18]:
X_train.head()

,age,study_hours_per_day,social_media_hours,netflix_hours,attendance_percentage,sleep_hours,exercise_frequency,mental_health_rating,gender_Female,gender_Male,...,diet_quality_Poor,parental_education_level_Bachelor,parental_education_level_High School,parental_education_level_Master,parental_education_level_UnEducated,internet_quality_Average,internet_quality_Good,internet_quality_Poor,extracurricular_participation_No,extracurricular_participation_Yes
29,20,2.0,3.2,3.8,82.6,6.7,6,10,True,False,...,True,False,True,False,False,False,False,True,False,True
535,22,6.4,4.2,1.5,88.8,6.1,0,6,True,False,...,False,False,True,False,False,False,True,False,True,False
695,20,2.5,1.9,1.6,93.6,7.0,4,8,True,False,...,False,True,False,False,False,False,True,False,True,False
557,22,3.8,3.6,4.3,100.0,7.3,1,7,False,True,...,True,True,False,False,False,False,False,True,False,True
836,19,3.5,2.8,0.0,92.0,3.8,5,5,False,True,...,False,False,False,False,True,False,False,True,False,True

In [19]:
y_train.head()

29     75.7
535    85.0
695    68.5
557    69.9
836    58.7
Name: exam_score, dtype: float64

In [20]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor ,GradientBoostingRegressor

In [21]:
models = {
    "LR" : LinearRegression(),
    "DT" : DecisionTreeRegressor(),
    "RF" : RandomForestRegressor(),
    "GB" : GradientBoostingRegressor()
}

In [22]:
for name , model in models.items():
    model.fit(X_train , y_train)

In [23]:
from sklearn.metrics import mean_absolute_error , mean_squared_error , r2_score

In [24]:
result = []

for name , model in models.items():
    y_pred = model.predict(X_test)
    
    mae = mean_absolute_error(y_test , y_pred)
    msr = mean_absolute_error(y_test , y_pred)
    r2 = r2_score(y_test , y_pred)

    result.append([name  , mae , msr , r2])

In [25]:
results_df = pd.DataFrame(result , columns=["Model" , "MAE" , "MSR" , "R2"])
print(results_df.sort_values(by="R2" , ascending = True))

  Model       MAE       MSR        R2
1    DT  7.456000  7.456000  0.655672
2    RF  5.021100  5.021100  0.846541
3    GB  4.676414  4.676414  0.879270
0    LR  4.189311  4.189311  0.896750

In [30]:

import torch 
import torch.nn as nn
import torch.optim as optim
from sklearn.preprocessing import StandardScaler

In [31]:
X.head()

,age,study_hours_per_day,social_media_hours,netflix_hours,attendance_percentage,sleep_hours,exercise_frequency,mental_health_rating,gender_Female,gender_Male,...,diet_quality_Poor,parental_education_level_Bachelor,parental_education_level_High School,parental_education_level_Master,parental_education_level_UnEducated,internet_quality_Average,internet_quality_Good,internet_quality_Poor,extracurricular_participation_No,extracurricular_participation_Yes
0,23,0.0,1.2,1.1,85.0,8.0,6,8,True,False,...,False,False,False,True,False,True,False,False,False,True
1,20,6.9,2.8,2.3,97.3,4.6,6,8,True,False,...,False,False,True,False,False,True,False,False,True,False
2,21,1.4,3.1,1.3,94.8,8.0,1,1,False,True,...,True,False,True,False,False,False,False,True,True,False
3,23,1.0,3.9,1.0,71.0,9.2,4,1,True,False,...,True,False,False,True,False,False,True,False,False,True
4,19,5.0,4.4,0.5,90.9,4.9,3,1,True,False,...,False,False,False,True,False,False,True,False,True,False

In [32]:
scaler = StandardScaler()

Xn_train = scaler.fit_transform(X_train.values)
Xn_test = scaler.transform(X_test.values)

In [35]:
Xn_train = torch.tensor(Xn_train , dtype=torch.float32)
Xn_test = torch.tensor(Xn_test  , dtype=torch.float32)

In [37]:
yn_train = torch.tensor(y_train.values , dtype = torch.float32).view(-1 , 1)
yn_test = torch.tensor(y_test.values , dtype = torch.float32).view(-1 , 1)

In [44]:
class ANN(nn.Module):
    def __init__(self , input_size):
        super(ANN , self ).__init__()

        self.model = nn.Sequential(
            nn.Linear(input_size , 32),
            nn.ReLU(),

            nn.Linear(32 , 16),
            nn.ReLU(),

            nn.Linear(16 , 1),
            
        )

    def forward(self , X):
        return self.model(X)

In [ ]:
input_size = Xn_train.shape[1]

Neural_Model = ANN(input_size=input_size)

criterion = nn.MSELoss()
optimiser = optim.Adam(Neural_Model.parameters() , lr = 0.1)

In [ ]:
epochs = 1000

for epoch in range(epochs):
    Neural_Model.train()

    output = Neural_Model(Xn_train)
    loss = criterion(output , yn_train)

    optimiser.zero_grad()
    loss.backward()
    optimiser.step()

    if epoch%10 == 0 :
        print(f"Epoch {epoch+1} , Loss : {loss.item():.4f}")

Epoch 1 , Loss : 5157.3452
Epoch 11 , Loss : 530.1487
Epoch 21 , Loss : 86.1551
Epoch 31 , Loss : 128.4178
Epoch 41 , Loss : 58.2986
Epoch 51 , Loss : 33.0254
Epoch 61 , Loss : 27.0991
Epoch 71 , Loss : 24.7142
Epoch 81 , Loss : 22.8751
Epoch 91 , Loss : 21.3187

In [47]:
Neural_Model.eval()

with torch.no_grad():
    predictions = Neural_Model(Xn_test)

In [48]:
y_pred = predictions.numpy()
y_true = yn_test.numpy()

In [49]:
from sklearn.metrics import mean_absolute_error, r2_score

mae = mean_absolute_error(y_true, y_pred)
r2 = r2_score(y_true, y_pred)

print("MAE:", mae)
print("R2:", r2)

MAE: 5.423880100250244
R2: 0.8194120526313782

# Try Different Structure

In [51]:
input_size

25

In [54]:
class ANN_1(nn.Module):
    def __init__(self , input_size):
        super(ANN_1 , self ).__init__()

        self.model = nn.Sequential(
            nn.Linear(input_size , 16),
            nn.ReLU(),

            nn.Linear(16 , 16),
            nn.ReLU(),

            nn.Linear(16 , 1),
            
        )

    def forward(self , X):
        return self.model(X)

In [55]:
input_size = Xn_train.shape[1]

Neural_Model_1 = ANN_1(input_size=input_size)

criterion = nn.MSELoss()
optimiser = optim.Adam(Neural_Model_1.parameters() , lr = 0.01)

In [56]:
epochs = 1000

for epoch in range(epochs):
    Neural_Model_1.train()

    output = Neural_Model_1(Xn_train)
    loss = criterion(output , yn_train)

    optimiser.zero_grad()
    loss.backward()
    optimiser.step()

    if epoch%10 == 0 :
        print(f"Epoch {epoch+1} , Loss : {loss.item():.4f}")

Epoch 1 , Loss : 5165.7349
Epoch 11 , Loss : 4999.2544
Epoch 21 , Loss : 4417.9517
Epoch 31 , Loss : 2970.5618
Epoch 41 , Loss : 961.7035
Epoch 51 , Loss : 406.7599
Epoch 61 , Loss : 190.9910
Epoch 71 , Loss : 147.8611
Epoch 81 , Loss : 106.1105
Epoch 91 , Loss : 91.9064
Epoch 101 , Loss : 79.1654
Epoch 111 , Loss : 71.6498
Epoch 121 , Loss : 65.1651
Epoch 131 , Loss : 59.9705
Epoch 141 , Loss : 55.8117
Epoch 151 , Loss : 52.2957
Epoch 161 , Loss : 49.4381
Epoch 171 , Loss : 47.0502
Epoch 181 , Loss : 45.0207
Epoch 191 , Loss : 43.2783
Epoch 201 , Loss : 41.7796
Epoch 211 , Loss : 40.4585
Epoch 221 , Loss : 39.2368
Epoch 231 , Loss : 38.1307
Epoch 241 , Loss : 37.1010
Epoch 251 , Loss : 36.1609
Epoch 261 , Loss : 35.2388
Epoch 271 , Loss : 34.2967
Epoch 281 , Loss : 33.3622
Epoch 291 , Loss : 32.4541
Epoch 301 , Loss : 31.5759
Epoch 311 , Loss : 30.7394
Epoch 321 , Loss : 30.0037
Epoch 331 , Loss : 29.3467
Epoch 341 , Loss : 28.7590
Epoch 351 , Loss : 28.2348
Epoch 361 , Loss : 27.7770
Epoch 371 , Loss : 27.3730
Epoch 381 , Loss : 26.9966
Epoch 391 , Loss : 26.6211
Epoch 401 , Loss : 26.2598
Epoch 411 , Loss : 25.8930
Epoch 421 , Loss : 25.5390
Epoch 431 , Loss : 25.2079
Epoch 441 , Loss : 24.9197
Epoch 451 , Loss : 24.6539
Epoch 461 , Loss : 24.3939
Epoch 471 , Loss : 24.1408
Epoch 481 , Loss : 23.8932
Epoch 491 , Loss : 23.6603
Epoch 501 , Loss : 23.4283
Epoch 511 , Loss : 23.2047
Epoch 521 , Loss : 23.0123
Epoch 531 , Loss : 22.8340
Epoch 541 , Loss : 22.6719
Epoch 551 , Loss : 22.4688
Epoch 561 , Loss : 22.2784
Epoch 571 , Loss : 22.0713
Epoch 581 , Loss : 21.8952
Epoch 591 , Loss : 21.7343
Epoch 601 , Loss : 21.5817
Epoch 611 , Loss : 21.4447
Epoch 621 , Loss : 21.3212
Epoch 631 , Loss : 21.1876
Epoch 641 , Loss : 21.0571
Epoch 651 , Loss : 20.9406
Epoch 661 , Loss : 20.8053
Epoch 671 , Loss : 20.6768
Epoch 681 , Loss : 20.5627
Epoch 691 , Loss : 20.4505
Epoch 701 , Loss : 20.3346
Epoch 711 , Loss : 20.2309
Epoch 721 , Loss : 20.1346
Epoch 731 , Loss : 20.0407
Epoch 741 , Loss : 19.9529
Epoch 751 , Loss : 19.8719
Epoch 761 , Loss : 19.7891
Epoch 771 , Loss : 19.7121
Epoch 781 , Loss : 19.6428
Epoch 791 , Loss : 19.5763
Epoch 801 , Loss : 19.4973
Epoch 811 , Loss : 19.4189
Epoch 821 , Loss : 19.3186
Epoch 831 , Loss : 19.2199
Epoch 841 , Loss : 19.1074
Epoch 851 , Loss : 19.0089
Epoch 861 , Loss : 18.9118
Epoch 871 , Loss : 18.8264
Epoch 881 , Loss : 18.7379
Epoch 891 , Loss : 18.6462
Epoch 901 , Loss : 18.5348
Epoch 911 , Loss : 18.4312
Epoch 921 , Loss : 18.3240
Epoch 931 , Loss : 18.1961
Epoch 941 , Loss : 18.0862
Epoch 951 , Loss : 17.9877
Epoch 961 , Loss : 17.8971
Epoch 971 , Loss : 17.7952
Epoch 981 , Loss : 17.7010
Epoch 991 , Loss : 17.6205

In [57]:
Neural_Model_1.eval()

with torch.no_grad():
    predictions = Neural_Model_1(Xn_test)

In [58]:
y_pred = predictions.numpy()
y_true = yn_test.numpy()

In [59]:
from sklearn.metrics import mean_absolute_error, r2_score

mae = mean_absolute_error(y_true, y_pred)
r2 = r2_score(y_true, y_pred)

print("MAE:", mae)
print("R2:", r2)

MAE: 6.06069278717041
R2: 0.7764325737953186